### ISSUE TITLE
仅支持map[string]string数据提交真的很蛋疼啊

### ISSUE THREAD

**Issue by liyisker** [thep0y/predator#2]
望下一个版本能加一个map[string]interface{}支持？

**Comment by thep0y** [comment]
> 望下一个版本能加一个map[string]interface{}支持？

可以的，但需要你提供一个场景（url、请求头、请求体）以便测试。

**Comment by liyisker** [comment]
没必要搭建什么环境吧？服务器端一般也无法验证数据类型。但是如果需要提交的一个JSON数据有很多，JSON里各种数据类型都有。无法直接序化成map[string]string{}，如果这个时候支持map[string]interface{}来提交DataFrom，很方便就可以将JSON转换成map来提交。而且map[string]string{}有一个致命的问题，多层嵌套的JSON基本无解。map[string]interface{}就灵活很多，基本没有这方面的困扰了

**Comment by thep0y** [comment]
> 没必要搭建什么环境吧？服务器端一般也无法验证数据类型。但是如果需要提交的一个JSON数据有很多，JSON里各种数据类型都有。无法直接序化成map[string]string{}，如果这个时候支持map[string]interface{}来提交DataFrom，很方便就可以将JSON转换成map来提交。而且map[string]string{}有一个致命的问题，多层嵌套的JSON基本无解。map[string]interface{}就灵活很多，基本没有这方面的困扰了

post的json请求体会在下次更新，至于是用`map[string]interface{}`还是直接用`[]byte`我正在考虑。

关于 POST 请求根据我的经验可分为三种：
- `form`表单：字符串键值对，已支持
- 可传文件的`form`表单：multipart/form-data，已支持
- json 请求体：暂未支持，下次更新会增加

因为整体进度是根据我自己的爬虫需求来的，当前的爬虫任务主要是`multipart/form-data`，所以`json`就向后推了。
