### ISSUE TITLE
建议加入自动重导向

### ISSUE THREAD

**Issue by musicyin** [thep0y/predator#3]
建议加入自动重导向
遇到回应响头有location或
body 有meta 的时侯

**Comment by thep0y** [comment]
加入后续更新计划，在下个版本中更新。
另外，我觉得重定向标识应该是状态码为301或302，而不是通过响应头的`location`字段或`body`。

**Comment by thep0y** [comment]
已添加 https://github.com/thep0y/predator/commit/d5acd482b19db53e1b7bf884e4d645a600ddc6fc
