### ISSUE TITLE
重定向回应问题

### ISSUE THREAD

**Issue by musicyin** [thep0y/predator#4]
重定向回应的set-cookie没有起作用

请求－＞301回应－＞重定向请求－＞页面回应set－cookie－>重定向请求没cookie

和建议加入以下功能，开crawler 的时候，可以调用cookiejar，方便以后提取cookie

**Comment by thep0y** [comment]
登录重定向通常会在响应头中传回一个`Set-Cookie`字段用作后续用户认证的标识，但需注意的是，这是爬虫，不是浏览器，不会保存`Set-Cookie`的值。
另外，请问你希望这个`301`响应的的`Set-Cookie`适用于后续所有请求，还是只是用来完成本次重定向的请求？

**Comment by musicyin** [comment]
我希望这个301响应的的Set-Cookie适用于后续所有请求，谢谢

**Comment by thep0y** [comment]
> 我希望这个301响应的的Set-Cookie适用于后续所有请求，谢谢

这正是我想要说的，我不打算因为某个重定向请求而影响全局的`crawler`，这是不明智的选择。
能提供一下你使用的具体场景吗？我需要根据具体情况考虑此功能是否应该添加。

**Comment by musicyin** [comment]
模凝登入，模凝提交表单，同时很多个线程，但不能用浏览器，因为cpu使用率很高

**Comment by thep0y** [comment]
不知道下面的代码能否解决你的问题
```go
func getRawCookie(c *Crawler) string {
	var rawCookie string

	c.AfterResponse(func(r *Response) {
		if r.StatusCode == 301 {
			rawCookie = string(r.Headers.Peek("Set-Cookie"))
		}
	})

	c.Post("/redirect", map[string]string{"username": "test", "password": "test"}, nil)

	return rawCookie
}

func main() {
	c := NewCrawler()

	rawCookie := getRawCookie(c)

	WithRawCookie(rawCookie)(c)
	WithConcurrency(10)(c)

	c.AfterResponse(func(r *Response) {
		fmt.Println(r.StatusCode)
		fmt.Println(r)
	})

	c.Get(ts.URL + "/check_cookie")
	c.Wait()
}
```

**Comment by musicyin** [comment]
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/thep0y/predator.WithRawCookie({0x0, 0x0})
	C:/Users/Administrator/go/pkg/mod/github.com/thep0y/predator@v0.1.5/options.go:85 +0x165

不行耶

**Comment by thep0y** [comment]
> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 1 [running]:
> github.com/thep0y/predator.WithRawCookie({0x0, 0x0})
> C:/Users/Administrator/go/pkg/mod/github.com/thep0y/predator@v0.1.5/options.go:85 +0x165
> 
> 不行耶

正常的 cookie 不会有此问题，你可能需要看看获取到的 rawCookie 是不是有什么问题。

**Comment by musicyin** [comment]
因为他是301到第三层回应才有setcookie
不知道是不是这个原因
我用net／http 很正常
用fasthttp就一直搞不好

**Comment by thep0y** [comment]
提供你的代码、使用场景等可以复现的信息

发自我的iPhone
